### ISSUE TITLE
Some sentences couldn't be translated (19 out of 679)

### ISSUE THREAD

**Issue by aseques** [Softcatala/nmt-softcatala#1]
The result after the process was quite good, but for some sentences there was an error.
> <_Rendezvous of RPC that terminated with:
> 	status = StatusCode.INVALID_ARGUMENT
> 	details = "indices[19,0,3] = [19, 0, 6] does not index into param shape [20,1,5,11]
> 	 [[{{node seq2seq/decoder_1/decoder_1/GatherNd}} = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _output_shapes=[[?,?,5,?]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](seq2seq/decoder_1/decoder_1/Reshape_2, seq2seq/decoder_1/decoder_1/stack)]]"
> 	debug_error_string = "{"created":"@1543102414.889922858","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"indices[19,0,3] = [19, 0, 6] does not index into param shape [20,1,5,11]\n\t [[{{node seq2seq/decoder_1/decoder_1/GatherNd}} = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _output_shapes=[[?,?,5,?]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](seq2seq/decoder_1/decoder_1/Reshape_2, seq2seq/decoder_1/decoder_1/stack)]]","grpc_status":3}"
> >
I've got no idea of what does it mean, but if you want them they I keep them.

**Comment by jordimas** [comment]
With Tensorflow 2.10 and OpenNMT 2.x this has been fixed. It happens very rarely now.
