### ISSUE TITLE
Phrasal verbs

### ISSUE THREAD

**Issue by tony47** [Softcatala/nmt-softcatala#11]
Hello,

Congratulations and thanks for your work.

I tried with some phrasal verbs and found that some are not working well. For example, I tried with "I get on well with him" or "don't let me down" and got incorrect translations.

**Comment by jordimas** [comment]
Hi Tony

The problem is that we do not have enought corpus with examples of these sentences, then the machine  cannot learn this. We need to continue improving the corpus.
