### ISSUE TITLE
Avaluació de la qualitat del traductor neural vs. Apertium anglès - català

### ISSUE THREAD

**Issue by jordimas** [Softcatala/nmt-softcatala#19]
#  Introducció
Actualment a Softcatalà disposem de dos traductors anglès català:

* https://www.softcatala.org/traductor/ (basat en motor Apertium i tecnologia de regles)
* https://www.softcatala.org/traductor-angles-catala/ (basat en motor OpenNMT i basat en xarxes neurals). Aquest tiquet descriu com s’està implementant inicialment.

Actualment els usuaris utilitzen la primera opció, que és l’opció per defecte.

Aquest document descriu quin criteri aplicarem per decidir si el traductor neural anglès - català passa o no a ser el nou traductor per defecte a Softcatalà per a aquest parell de llengües. Hem de garantir dues coses:

* Que la velocitat de traducció del traductor neural sigui acceptable pels nostres sistemes
* Que una avaluació metòdica demostra que té una millor qualitat

# Avaluació de la velocitat de traducció

Actualment tenim mensualment:
* 150k - 200k traduccions anglès - català o català - anglès
* 2/3 és el màxim de traduccions simultànies 

Desconeixem ara mateix la mida de les traduccions.

Hauríem de garantir que el traductor:

* Gestiona correctament fins a 3 vegades el tràfic actual de X peticions de X mida per segon (jo agafaria els horaris amb més peticions) usant menys del 50% dels recursos de la màquina

# Avaluació de la qualitat de traducció

## Repte

Respecte a les mètriques d’avaluació automàtica, el que funciona en un corpus pot no funcionar en un altre. 

Per dir-ho d'una manera senzilla, no hi ha cap mètrica que garanteixi completament que un sistema és millor que un altre. Això es deu al fet que no existeix tal com una única traducció "millor", sinó també al fet que les diferents tasques tenen diferents interpretacions del que constitueix una bona traducció, adequada per a finalitats.

### Preparació del corpus

* Crear un corpus de 400 frases (400 en direcció anglès - català i 400 en català - anglès) basat en traduccions recollides de les usuaris demanin al nostre traductor (a través de https://www.softcatala.org/traductor-angles-catala/)
* Seleccionar textos de més 3 paraules
* Si un text d’un mateix usuari té més d’una frase només agafem la primera (per tenir-ne el corpus el més variat possible)
* Traduir-les nosaltres manualment per tal de tenir un corpus de referència 
* Llavors traduir-les amb Apertium i el traductor neural de forma automàtica

### Avaluació

Ens basem en un enfocament similar al que va usar Google quan va desenvolupar el seu neural, combinant avaluació automàtica amb humans.

Fer una avaluació per humans de les 800 cadenes traduïdes pels dos traductors amb tres objectius (veure assimilació vs dimeminació)

* Valorar la qualitat de la traducció d’1 a 6 l’assimilació de text:
    * 0 - si és una traducció sense sentit
    * 2  - si la frase conserva part del significat de la frase original però troba a faltar parts significatives
    * 4 - si la frase conserva la major part del significat de la frase original, però pot tenir alguns errors gramaticals
    * 6 significant "traducció perfecta: el significat de la traducció és completament consistent amb la font, i la gramàtica és correcta". 

Valorar la qualitat de la traducció per diseminació. Per fer-ho:

* Demanar als traductors corregir la traducció perque sigui publicable 
* Calcular els canvis entre les dues versions usant BLUE
* Calcular la mètrica BLEU de les dues traduccions
* BLEU és una mesura de corpus, llavors ens dona una vista global de la qualitat de la traducció

**Comment by xavivars** [comment]
Per a fer les avaluacions del cas d'ús d'assimilació, segons qui faça l'avaluació, el mètode proposat pot no ser efectiu. El que s'acostuma a fer en traducció automàtica és fer proves de comprensió: amagant el text original i amb preguntes tipus test o amb exercicis tipus "ompli el forat" que requereixen entendre bé la traducció per a saber què diu.
I en el cas de disseminació, mesurar el temps de postedició.
