### ISSUE TITLE
Error de compilació

### ISSUE THREAD

**Issue by wagafo** [Softcatala/nmt-softcatala#32]
Estic intentant la compilació a un sistema amb l'Ubuntu 24.04. M'apareix el següent error:

make build-all
docker build -t nmt-models . -f models/docker/Dockerfile;
[+] Building 52.3s (11/29)                                       docker:default
 => [internal] load .dockerignore                                          0.7s
 => => transferring context: 70B                                           0.2s
 => [internal] load build definition from Dockerfile                       0.7s
 => => transferring dockerfile: 2.37kB                                     0.2s
 => [internal] load metadata for docker.io/library/python:3.11.0-slim-bul  6.1s
 => [generate_data  1/25] FROM docker.io/library/python:3.11.0-slim-bulls  4.7s
 => => resolve docker.io/library/python:3.11.0-slim-bullseye@sha256:b5ee5  0.0s
 => => sha256:15faa1ce7d77d3884c0ef3348f17bb06d7a57b2c3b4 7.49kB / 7.49kB  0.0s
 => => sha256:025c56f98b679f70b7a54241917e56da7b59ab9d2 31.41MB / 31.41MB  1.0s
 => => sha256:778656c04542093db6d3b6e07bffbcf6ec4b2470927 1.08MB / 1.08MB  0.5s
 => => sha256:3275e90747232f394d7b8fc9a2b481e07a4454f13 12.59MB / 12.59MB  0.6s
 => => sha256:b5ee5360b357dcd0ab2e1cc5e22fa589b6734bbd557 1.65kB / 1.65kB  0.0s
 => => sha256:ff09e30b44097b761742f1c460f385046d3627c1cfd 1.37kB / 1.37kB  0.0s
 => => sha256:9c14766361e2de1409b3695c1e1e5ca7eb92b0fb3699516 232B / 232B  0.7s
 => => sha256:5882f66f020b95daabdb82684a5a0d9c98cf961cf52 3.35MB / 3.35MB  0.8s
 => => extracting sha256:025c56f98b679f70b7a54241917e56da7b59ab9d2defecc6  1.8s
 => => extracting sha256:778656c04542093db6d3b6e07bffbcf6ec4b24709276be7c  0.1s
 => => extracting sha256:3275e90747232f394d7b8fc9a2b481e07a4454f13e17c356  0.6s
 => => extracting sha256:9c14766361e2de1409b3695c1e1e5ca7eb92b0fb36995167  0.0s
 => => extracting sha256:5882f66f020b95daabdb82684a5a0d9c98cf961cf52870c6  0.3s
 => [generate_data  2/25] RUN apt-get update && apt-get -y upgrade && ap  22.6s
 => [generate_data  3/25] RUN mkdir models                                 0.4s
 => [generate_data  4/25] WORKDIR models                                   0.0s
 => [generate_data  5/25] RUN wget -q https://www.softcatala.org/pub/soft  5.4s
 => [generate_data  6/25] RUN wget -q https://www.softcatala.org/pub/soft  5.4s
 => [generate_data  7/25] RUN wget -q https://www.softcatala.org/pub/soft  5.4s
 => ERROR [generate_data  8/25] RUN wget -q https://www.softcatala.org/pu  0.5s
------
 > [generate_data  8/25] RUN wget -q https://www.softcatala.org/pub/softcatala/opennmt/models/2022-11-22/cat-fra-2022-11-14.zip && unzip cat-fra-2022-11-14.zip -x */tensorflow/*:
------
Dockerfile:20
--------------------
  18 |     
  19 |     ENV FILE cat-fra-2022-11-14.zip
  20 | >>> RUN wget -q $URL/$FILE && unzip $FILE -x */tensorflow/*
  21 |     
  22 |     ENV FILE cat-glg-2022-11-21.zip
--------------------
ERROR: failed to solve: process "/bin/sh -c wget -q $URL/$FILE && unzip $FILE -x */tensorflow/*" did not complete successfully: exit code: 8
make: *** [Makefile:4: docker-build-models] Error 1

**Comment by jordimas** [comment]
It should be fixed now. Let me know if it works. Thanks

**Comment by wagafo** [comment]
Thanks, it works "com la seda"...

**Comment by jordimas** [comment]
Gràcies! Qualsevol cosa obre un altre ticket
