### ISSUE TITLE
Underscore and carriage returns ignored

### ISSUE THREAD

**Issue by wagafo** [Softcatala/nmt-softcatala#33]
Underscore and carriage returns are ignored in the translation, for instance:

#: dwarf.c:2461
#, fuzzy
msgid "Internal error: DW_FORM_ref_addr is not supported in DWARF version 1.\n"
msgstr ""
"Error intern: DWFORMrefaddr no és compatible amb la versió 1 de DWARF."

**Comment by jordimas** [comment]
The \n should be fixed now. You need to git pull again and build the image.

For things like DW_FORM_ref_addr we do not have a good solution at the moment since it is due how the model translate unseen words.

**Comment by jordimas** [comment]
This is fixed. If there is a problem, please open it again
